### ISSUE TITLE
No button for sending email - reCAPTCHA error on feedback page

### ISSUE THREAD

**Issue by ivardj** [dbmedialab/reader-critics#658]
After submitting a critic of a page, there is a field for leaving name and email, but no button to submit this. There is either a link back to the article or a feedback link for the tool. When clicking on the feedback link for the tool, there is a reCAPTCHA connection issue, preventing the user from providing actual feedback.

This has happened to me on two different pages with different browsers.

**Comment by phgroe** [comment]
Good morning and thank you for the feedback! This is our first external issue :sparkles:

- The send button in the final feedback form has indeed disappeared.
- The problem with the Recaptcha is known, we have to reconfigure the domain/API key for this.

Both will be addressed shortly!

**Comment by phgroe** [comment]
#659 has been deployed to all systems.

Also the domain key for the Recaptcha has been updated. According to Google, this will take a short while to take effect.

**Comment by phgroe** [comment]
Recaptcha working fine on all production domains. All good!

/close
